exclude: 'build'

default_language_version:
    python: python3

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 6306a48f7dae5861702d573c9c247e4e9498e867
    hooks:
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: check-added-large-files
        args: ['--maxkb=500']
    -   id: end-of-file-fixer
        exclude: '^(.*\.svg)$'

-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.0
    hooks:
        # Run the linter.
        - id: ruff

-   repo: https://github.com/omnilib/ufmt
    rev: v2.3.0
    hooks:
    -   id: ufmt
        additional_dependencies:
          - black == 23.3.0
          - usort == 1.0.6
