# Basic flak8 + pytest workflow for Python 3.10

name: Python Lint and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install -U --pre torch --index-url https://download.pytorch.org/whl/nightly/cu121
        pip install -e .
        pip install -e .'[dev]'
        pip install -e .'[test]'
    - name: Lint with ruff
      run: |
        ruff check .
    - name: Running Tests
      run: |
        ./test/test_everything.sh
